### ISSUE TITLE
permission denied while trying to connect docker pull

### ISSUE THREAD

**Issue by bngcebetsha** [ratt-ru/parrot-stew-recipes#4]
I'm failing at the "preparation" step. here is the short log
```
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO: ### validated inputs
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO: cab flagmanager:
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO:   versionname = init
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO:   mode = save
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO:   ms = /home/bngcebetsha/Proxima_short_epochs/msdir/1616737569_sdp_l0-Proxima_Cen-corr-scan03.ms
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO: singularity auto-update: pulling and inspecting docker image
### running /usr/bin/docker pull quay.io/stimela2/casa:cc0.0.2
# permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=quay.io%2Fstimela2%2Fcasa&tag=cc0.0.2": dial unix /var/run/docker.sock: connect: permission denied
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init INFO: (docker pull) exited with code 1 after 0:00:00
2024-11-23 07:41:53 STIMELA.jove-prepare.flagsave-init ERROR: step 'jove-prepare.flagsave-init' has failed, aborting the recipe
```
The path I am working in is `young:/home/bngcebetsha/Proxima_short_epochs/parrot-stew-recipes` - I edited the recipe to point to the location of my `caracal`-corrected MS here `/home/bngcebetsha/Proxima_short_epochs/msdir`.

I tried to do `docker login` which usually solves this kind of thing, 
```
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: bngcebetsha
Password:
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: co
nnect: permission denied
```

**Comment by o-smirnov** [comment]
We don't give regular users docker permissions at Rhodes, but you should be able to run with Singularity. Just put

```
opts:
  backend:
    select: signularity
```

into your configuration.

That said, I think you should rather be running @JSKenyon's revamped and stripped-down pipeline. He should be back from leave now-now and can advise. Sorry abut the confusion, my fault, I misuse the term "PARROT pipeline" for both this original one, and @JSKenyon's cleaned up version (which we also call the "reference pipeline"). You can run the original one for practice while you wait for Jon's reply, the reference pipeline is broadly similar in the sequence of steps, just doesn't have the PARROT-field-specific tunings that might cause confusion here.

@JSKenyon, please ping us when you're back in the saddle, we have a very exciting idea to try here.

**Comment by bngcebetsha** [comment]
Oh thanks for the quick response. I was about to edit this issue title to "Things I had to tweak to get things running" and post the following:
``` sh
pip install python-casacore
stimela run jove-<step>.yml scan=3  # since my scan number is 3
pip install cubical
pip install breizorro
```
And yes, I had to change all `backend` arguments to `native`. Running things as practice for now

**Comment by bngcebetsha** [comment]
Going to close this as its no longer an issue, I found @JSKenyon 's version here - https://github.com/JSKenyon/lightcurve-pipeline which looks like a good way to start.

**Comment by JSKenyon** [comment]
Glad that you managed to find it. We can address further issues on the lightcurve-pipeline repo.
